### ISSUE TITLE
Cannot start the latest version (4.7) of SpotCommander

### ISSUE THREAD

**Issue by Wnt** [olejon/spotcommander#75]
Application fails to start up and I can see the following message in th system logs. Please note that I'm running on a non-standard Android platform: the Jolla phone. The previous version, 4.6 ran OK on the same device.

```
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.olejon.spotcommander/net.olejon.spotcommander.MainActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2066)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2091)
        at android.app.ActivityThread.access$600(ActivityThread.java:137)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4781)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
        at net.olejon.spotcommander.MainActivity.onCreate(MainActivity.java:95)
        at android.app.Activity.performCreate(Activity.java:5008)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2030)
        ... 11 more
```

**Comment by Wnt** [comment]
Actually it seems than now even the previous version (4.6) gives the same error in the system log and fails to start up.

**Comment by olejon** [comment]
That's weird. Maybe there has been some update to Jolla's Android environment? Experiencing problems with other Android apps?

Unfortunately the debug you provide gives me no clues... Changes between 4.6 and 4.7 are minimal.

**Comment by olejon** [comment]
Does it work now? If not, I suggest you uninstall SpotCommander, then reboot your device and reinstall SpotCommander.

Note that SpotCommander is available in F-Droid. You can install from there, so you'll get updates.

**Comment by olejon** [comment]
Again, does it work now? I don't know how you installed SpotCommander, but it is available on [F-Droid](https://f-droid.org/) now, so you may try to install from there.

**Comment by olejon** [comment]
SpotCommander is now available on Jolla Harbour. Maybe try to install from there?

**Comment by Wnt** [comment]
That's great news! I'm still having the same problem as before. There must be something broken in my Android environment as all the apps go through Jolla QA before getting accepted there.

**Comment by olejon** [comment]
Yes, I have emailed with the Jolla team and they were able to open the app indeed.

I suggest you take this further within the Jolla support community. Ask other users if they can try to install and open the app. They don't need a Linux computer just to install and open.

Surprisingly I already have 22 active installs.
